# -*- coding: utf-8 -*-
"""matriz_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwQP7uk-2nu9UaGRJcEWtgqcgo1L8aMu
"""

import pandas as pd

class MatrizDados:
 def __init__(self, dados=None):
  self.elementos = dados if dados is not None else []

 def obter_valor(self, linha, coluna):
  """Obtém um valor específico da matriz."""
  if self.elementos is not None and isinstance(self.elementos, pd.DataFrame):
   try:
    return self.elementos.iloc[linha, coluna]
   except:
    return None
  return None

 def definir_valor(self, linha, coluna, valor):
  """Define um valor específico na matriz."""
  if self.elementos is not None and isinstance(self.elementos, pd.DataFrame):
   try:
    self.elementos.iloc[linha, coluna] = valor
    return True
   except:
    return False
  return False