# -*- coding: utf-8 -*-
"""resultado_emergia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109UJNGeYbbjJ-gI47popAb5Y_9_FnP96
"""

class ResultadoEmergia:
 def __init__(self):
  self.valor_total = 0.0
  self.sumario_descritivo = ""

 def formatar_para_exibicao(self):
  """Formata o resultado para exibição na interface."""
  # Converter número em notação científica para decimal por extenso
  def converter_notacao_cientifica(numero):
   valor_decimal = f"{numero:.10f}"
   valor_decimal = valor_decimal.rstrip("0").rstrip(".") if "." in valor_decimal else valor_decimal
   return valor_decimal

  resultado_decimal = converter_notacao_cientifica(self.valor_total)
  return {
   "emergia_total_cientifica": f"{self.valor_total:.5E}",
   "emergia_total_decimal": resultado_decimal,
   "sumario": self.sumario_descritivo
  }